services:

  db:
    image: postgres
    container_name: anssi-nis2-db
    restart: always
    networks:
      - nis2
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: anssi-nis2-api
    build:
      context: .
      dockerfile: Dockerfile-api
    networks:
      - nis2
    ports:
      - "4000:3000"
    volumes:
      - ./anssi-nis2-api:/usr/src/app/anssi-nis2-api
      - ./commun:/usr/src/app/commun
      - ./anssi-nis2-ui/dist:/usr/src/app/anssi-nis2-ui/dist
    depends_on:
      db:
        condition: service_healthy

networks:
  nis2:
    external: true