import { ReactNode } from "react";
import { TValeursActivites } from "./ValeursCles.ts";

export const DescriptionActivite: Record<TValeursActivites, ReactNode> = {
  acteurDuMarche: undefined,
  administrationPouvoirsPublicsCentraux: undefined,
  administrationPubliqueNiveauRegional: undefined,
  autoritesRoutieresControleGestionCirculation: undefined,
  autre: undefined,
  collectantEvacuantTraitantEaux: undefined,
  constructionAeronautiqueSpatiale: undefined,
  constructionBateauxNaviresMilitaires: undefined,
  constructionBateauxPlaisance: undefined,
  constructionLocomotivesAutreMaterielFerroviaireRoulant: undefined,
  constructionNavale: undefined,
  constructionNaviresStructuresFlottantesCiviles: undefined,
  constructionVehiculeMilitaireCombat: undefined,
  constructionVehiculesAutomobiles: undefined,
  contrepartieCentrales: undefined,
  entiteCentralesStockage: undefined,
  entiteGestionnaireAeroports: undefined,
  entiteGestionnairePorts: undefined,
  entrepriseElectriciteRemplissantFonctionFourniture: (
    <>
      <h3>Entreprise d’électricité</h3>
      <p>
        Toute personne physique ou morale qui assure au moins une des fonctions
        suivantes : la production, le transport, la distribution,
        l&quot;agrégation, la participation active de la demande, le stockage
        d&quot;énergie, la fourniture ou l&quot;achat d&quot;électricité et qui
        est chargée des missions commerciales, techniques ou de maintenance
        liées à ces fonctions, à l&quot;exclusion des clients finaux.
      </p>
      <h3>Fourniture</h3>
      <p>La vente, y compris la revente, d&quot;électricité à des clients.</p>
    </>
  ),
  entrepriseFerroviaire: undefined,
  entrepriseFourniture: undefined,
  etablissementCredit: undefined,
  executantOperationGestionDechets: undefined,
  exploitantsInfrastructureTerrestresFournitureServicesSpaciaux: undefined,
  exploitantsInstallationPetrole: undefined,
  exploitantsOleoduc: undefined,
  exploitantsPlateformesNegociation: undefined,
  exploitantsPointRecharge: undefined,
  exploitantsServiceTrafficMaritime: undefined,
  exploitantsSystemeHydrogene: undefined,
  exploitantsSystemeTransportIntelligents: undefined,
  fabricationDistributionSubstances: undefined,
  fabricationMaterielTransportNCA: undefined,
  fabriquantAppareilEclairage: undefined,
  fabriquantAppareilsMenagers: undefined,
  fabriquantAutresMachinesUsageGeneral: undefined,
  fabriquantAutresMachinesUsageSpecifiqueNCA: undefined,
  fabriquantCarrosseriesVehiculesAutomobiles: undefined,
  fabriquantComposantCartesElectroniques: undefined,
  fabriquantDispositifsMedicaux: undefined,
  fabriquantDispositifsMedicauxCritiques: undefined,
  fabriquantEquipementCommunication: undefined,
  fabriquantEquipementIrradiationMedicaleElectromedicauxElectrotherapeutiques:
    undefined,
  fabriquantEquipementsAutomobiles: undefined,
  fabriquantFilsCablesMaterielInstallationElectrique: undefined,
  fabriquantInstrumentsMesureEssaiNavigationHorlogerie: undefined,
  fabriquantMachineEquipementNCA: undefined,
  fabriquantMachineUsageGeneral: undefined,
  fabriquantMachinesAgricolesForestieres: undefined,
  fabriquantMachinesFormageMetauxMachinesOutils: undefined,
  fabriquantMaterielOptiquePhotographiquesSupportsMagnetiquesOptiques:
    undefined,
  fabriquantMoteursGeneratriceTransformation: undefined,
  fabriquantOrdinateursEquipementsPeripheriques: undefined,
  fabriquantPilesAccumulateursElectriques: undefined,
  fabriquantProduitPreparationsPharmaceutiques: undefined,
  fabriquantProduitsElectroniquesGrandPublic: undefined,
  fabriquantProduitsInformatiquesElectroniquesOptiques: undefined,
  fournisseurPointEchangeInternet: undefined,
  fournisseurReseauxCommunicationElectroniquesPublics: undefined,
  fournisseurReseauxDiffusionContenu: undefined,
  fournisseurServiceCentresDonnees: undefined,
  fournisseurServiceCommunicationElectroniquesPublics: undefined,
  fournisseurServicesDNS: undefined,
  fournisseurServicesGeres: undefined,
  fournisseurServicesInformatiqueNuage: undefined,
  fournisseurServicesSecuriteGeres: undefined,
  fournisseursDistributeursEauxConsommation: undefined,
  fournisseursMoteursRechercheEnLigne: undefined,
  fournisseursPlaceMarcheEnLigne: undefined,
  fournisseursPlateformesServicesReseauxSociaux: undefined,
  gestionnaireInfrastructure: undefined,
  gestionnaireInstallationGNL: undefined,
  gestionnaireInstallationStockage: undefined,
  gestionnaireReseau: undefined,
  gestionnaireReseauDistribution: undefined,
  gestionnaireReseauTransport: undefined,
  laboratoireReferenceUE: undefined,
  operateurDesigneMarcheOuNemo: undefined,
  operateurReseauChaleurFroid: undefined,
  organismeRecherche: undefined,
  prestataireServiceConfiance: undefined,
  prestataireSoinsSante: undefined,
  prestatairesServicesPostauxExpedition: undefined,
  producteur: undefined,
  rechercheDeveloppementMedicament: undefined,
  registresNomsDomainesPremierNiveau: undefined,
  secteurAlimentaireDistributionGrosProductionTransformationIndustrielle:
    undefined,
  serviceControleCirculationAerienne: undefined,
  societeTransportEaux: undefined,
  transporteursAeriensCommercial: undefined,
};
