name: L'intégration continue

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configuration de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      - name: Installation des dépendances
        run: npm ci

      - name: Vérification des règles de code
        run: npm run lint

      - name: Lancement des tests unitaires
        run: npm test

      - name: Construction des applications
        run: npm run build --if-present