name: Node.js CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Installation des dépendances
        run: npm ci
      - name: Vérification des règles de code
        run: npm run lint
      - name: Lancement des tests unitaires
        run: npm test
      - name: Construction des applications
        run: npm run build --if-present
